"""empty message

Revision ID: e86a6ff871dc
Revises: 
Create Date: 2021-03-30 00:39:19.606630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86a6ff871dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('weight_rating', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notseen_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('naver_movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_original', sa.String(), nullable=True),
    sa.Column('title_kr', sa.String(), nullable=True),
    sa.Column('pubdate', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('director', sa.String(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.movie_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.movie_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keep_movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('naver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.movie_id'], ),
    sa.ForeignKeyConstraint(['naver_id'], ['naver_movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_rating', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('naver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['rating_users.movie_id'], ),
    sa.ForeignKeyConstraint(['naver_id'], ['naver_movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('render_movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('naver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.movie_id'], ),
    sa.ForeignKeyConstraint(['naver_id'], ['naver_movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('render_movies')
    op.drop_table('rating_client')
    op.drop_table('keep_movies')
    op.drop_table('rating_users')
    op.drop_table('naver_movies')
    op.drop_table('notseen_client')
    op.drop_table('movies')
    # ### end Alembic commands ###
